services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data

  trino:
    image: trinodb/trino:426
    container_name: trino
    ports:
      - "8080:8080"
    volumes:
      - ./datalake.properties:/etc/trino/catalog/datalake.properties
      - ./trino_metadata:/data/trino_metadata
    depends_on:
      - minio